version: '3.2' # specify docker-compose version

# Define the services/ containers to be run
services:
    client: # name of the first service
        build: client # specify the directory of the Dockerfile
        ports:
        - "4200:3000" # specify port mapping
        volumes:
            - ./client:/usr/src/app
    server: # name of the second service
        build: server # specify the directory of the Dockerfile
        ports:
        - "3000:3000" #specify ports mapping
        links:
        - mongodb # link this service to the database service
        volumes:
        - ./server:/usr/src/app
    mongodb: # name of the third service
        image: mongo # specify image to build container from
        ports:
        - "27017:27017" # specify port forwarding
        volumes:
        - ./mongodb:/data/db